function providerInit = initiate_restart_provider(init_format, run_name, result_path, source_path, constant_file)
%INITIATE_RESTART_PROVIDER  Construct a PROVIDER object for parallel restart simulations
%
% This function creates and configures a CryoGrid PROVIDER object that is
% specifically designed to restart simulations from previously generated
% OUT_last_timestep files.
%
% The function combines:
%   - the standard parameter modifications from NEW_PARAMS.xlsx,
%   - restart-specific output settings from RESTART.xlsx,
%   - and a two-loop spinup structure generated by create_model_loops().
%
% The resulting PROVIDER is configured so that each restart simulation can
% read an existing restart file and write only the desired restart outputs,
% making it suitable for launching multiple independent continuation runs.
%
%
% INPUTS
% ------
% init_format   (char|string)
%     Initialization format identifier used by CryoGrid.
%
% run_name      (char|string)
%     Name of the simulation run.
%
% result_path   (char|string)
%     Root directory containing simulation inputs and outputs.
%
% source_path   (char|string)
%     Path to the CryoGrid source code.
%
% constant_file (char|string)
%     Name of the CryoGrid constant parameter file.
%
%
% OUTPUT
% ------
% providerInit  (PROVIDER)
%     Fully configured PROVIDER object ready to restart from existing
%     OUT_last_timestep files.
%
%
% DESCRIPTION
% -----------
% The function performs the following steps:
%
%   1. Load the parameter modifications defined in NEW_PARAMS.xlsx.
%
%   2. Load the restart-specific configuration defined in RESTART.xlsx.
%
%   3. Apply the NEW_PARAMS modifications to the restart provider.
%
%   4. Construct a two-loop provider using create_model_loops().
%
%   5. Remove the initial spinup tile so that execution starts directly
%      from the restart configuration.
%
%   6. Replace all OUT_* classes with those defined in RESTART.xlsx.
%
%   7. Configure the restart tile to:
%        - use the restart output classes,
%        - assign corresponding output indices,
%        - use the appropriate forcing object.
%
%
% SEE ALSO
% --------
% construct_provider, modify_parameters, create_model_loops,
% shift_to_next_tile

%create and load PROVIDER for the initial loop
providerNew = construct_provider(init_format, run_name, result_path, constant_file, 'NEW_PARAMS');
providerRestart = construct_provider(init_format, run_name, result_path, constant_file, 'RESTART');
providerRestart = modify_parameters(providerRestart, providerNew);

providerInit = create_model_loops(init_format, run_name, result_path, source_path, constant_file, 1);
providerInit = shift_to_next_tile(providerInit, 1);

fns = fieldnames(providerRestart.CLASSES);
fns = fns(contains(fns, 'OUT_'));
for i = 1:size(fns,1)
    f = fns{i};
    providerInit.CLASSES.(f) = providerRestart.CLASSES.(f);
end

providerInit.CLASSES.TILE_1D{3,1}.PARA.out_class = fns;
providerInit.CLASSES.TILE_1D{3,1}.PARA.out_class_index = ones(size(fns,1),1);
providerInit.CLASSES.TILE_1D{3,1}.PARA.forcing_class_index = 1;

end
