function write_individual_loop_folders(numLoops, providerInit)
%WRITE_INDIVIDUAL_LOOP_FOLDERS  Create restart folders for independent spinup loops
%
% This function creates a dedicated directory for each spinup loop and
% prepares all files required to launch an independent restart simulation.
%
% For every loop, the corresponding OUT_last_timestep restart file and the
% CryoGrid constant parameter file are copied into a separate folder with
% standardized names suitable for automated restart workflows.
%
%
% INPUTS
% ------
% numLoops      (integer)
%     Number of spinup loops to prepare.
%
% providerInit  (PROVIDER)
%     PROVIDER object containing forcing information, run metadata and
%     output paths generated by create_model_loops().
%
%
% OUTPUT
% ------
% None.
%
%
% DESCRIPTION
% -----------
% For each loop n = 0, ..., numLoops, the function:
%
%   1. Creates the directory
%
%          <result_path>/<run_name>/loop<n>/
%
%      if it does not already exist.
%
%   2. Determines the corresponding OUT_last_timestep restart file from
%      the forcing end date and tile numbering convention.
%
%   3. Copies the CryoGrid constant parameter file into the loop folder.
%
%   4. Copies and renames the restart MAT-file to
%
%          <run_name>_loop<n>.mat
%
%      allowing each loop directory to be executed independently.
%
%   5. Creates an excel parameter file from the provider class
%
% The resulting folder structure contains all files required to start a
% restart simulation without modifying the original spinup outputs.
%
%
% SEE ALSO
% --------
% create_model_loops, initiate_restart_provider

result_path = string(providerInit.PARA.result_path);
run_name = string(providerInit.PARA.run_name);
constant_file = string(providerInit.PARA.constant_file);

new_result_path = result_path + run_name + "\";

for n = 0:numLoops
    new_run_name = "loop" + string(n);
    folder = new_result_path + new_run_name + "\";
    if ~exist(folder, 'dir')
        mkdir(folder);
    end

    idxForcing = 1;
    if n > 0
        idxForcing = 2;
    end

    endTime = providerInit.CLASSES.FORCING_seb_mat{idxForcing,1}.PARA.end_time;
    endTime = string(datetime(endTime','Format','yyyyMMdd'));
    file = sprintf("%s_tile%d_run1_%s_last_timestep", run_name, 2*n+1, endTime);

    % Write to Excel
    path_out = [folder new_run_name '.xlsx'];
    if isfile(path_out)
        try
            delete(path_out);
        catch
            warning("Could not delete file: %s", path_out);
        end
    end

    copyfile(constant_file,folder)
    copyfile(new_result_path+file+".mat",folder+run_name+"_"+new_run_name+".mat")



    % PROVIDER local (important)
    providerLoop = providerInit;
    providerLoop.CLASSES.TILE_1D{2,1} = copy(providerInit.CLASSES.TILE_1D{2,1});
    providerLoop.CLASSES.TILE_1D{2,1}.PARA.restart_file_path = char(folder);
    providerLoop.CLASSES.TILE_1D{2,1}.PARA.restart_file_name = char(run_name+"_"+new_run_name);

    % providerLoop.PARA = copy(providerInit.PARA);
    providerLoop.PARA.run_name = char(new_run_name);
    providerLoop.PARA.result_path = char(new_result_path);

    provider_to_parameter_file_excel(providerLoop, char(new_result_path), char(new_run_name))


end

end