function Rchunk = make_chunk_reference( ...
    R,row1,row2,col1,col2)

x1 = R.XWorldLimits(1) + ...
    (col1-1)*R.CellExtentInWorldX;

x2 = R.XWorldLimits(1) + ...
    col2*R.CellExtentInWorldX;

y2 = R.YWorldLimits(2) - ...
    (row1-1)*R.CellExtentInWorldY;

y1 = R.YWorldLimits(2) - ...
    row2*R.CellExtentInWorldY;

Rchunk = maprefcells( ...
    [x1 x2], ...
    [y1 y2], ...
    [row2-row1+1,col2-col1+1], ...
    "ColumnsStartFrom","north", ...
    "RowsStartFrom","west");

try
    Rchunk.ProjectedCRS = R.ProjectedCRS;
catch
end

end
