function write_svf_geotiff(filename,SVF,R)
%WRITE_SVF_GEOTIFF Write SVF raster with projected CRS metadata.

% The Alpine DEM uses Lambert-93 / EPSG:2154.
geotiffwrite( ...
    filename, ...
    SVF, ...
    R, ...
    "CoordRefSysCode",2154);

end
