function run_lidar_diagnostics(dem_folder,safran_shp,save_folder)
%RUN_LIDAR_DIAGNOSTICS Run LiDAR DEM quality-control workflow.
%
% DESCRIPTION
%   Generates diagnostic figures and validation tables for the LiDAR HD
%   DEM products generated by prepare_dem().
%
%   The workflow validates individual SAFRAN massif DEMs and, if available,
%   also generates an overview of the merged Alpine DEM produced by
%   merge_massif_DEMs().
%
%
% INPUTS
%
%   dem_folder
%       Folder containing LiDAR DEM products:
%
%           DEM_massif_XX.tif
%           DEM_mask_massif_XX.tif
%
%       and optionally:
%
%           ALPS/
%               DEM_ALPS.tif
%               DEM_ALPS_mask.tif
%
%   safran_shp
%       SAFRAN massif shapefile in Lambert-93 (EPSG:2154).
%
%   save_folder
%       Output folder for diagnostic figures and validation tables.
%
%
% OUTPUT
%
%   Creates:
%
%       LiDAR_HD_DEM_massifs.png
%           Overview of individual SAFRAN massif DEMs.
%
%       LiDAR_HD_DEM_ALPS_overview.png
%           Overview of merged Alpine DEM (if available).
%
%       LiDAR_HD_DEM_missing_pixels.png
%           Spatial distribution of missing DEM pixels.
%
%       LiDAR_HD_DEM_validation.csv
%           Validation statistics per massif.
%
%       LiDAR_HD_DEM_validation.md
%           Markdown version of validation table.
%
%
% NOTES
%
%   The Alpine DEM overview is only generated if:
%
%       ALPS/DEM_ALPS.tif
%       ALPS/DEM_ALPS_mask.tif
%
%   are present.
%
%
% SEE ALSO
%
%   prepare_dem
%   merge_massif_DEMs
%   plot_alps_dem
%   validate_lidar_dem
%


if ~exist(save_folder,"dir")
    mkdir(save_folder)
end

%% DEM overview

fprintf("\nCreating DEM overview...\n")

OUT = plot_all_lidar_massifs( ...
    dem_folder,...
    safran_shp,...
    save_folder);

%% Missing pixels

fprintf("\nCreating missing pixel plot...\n")
plot_lidar_missing_pixels(OUT,save_folder);

%% Validation

fprintf("\nCreating validation table...\n")
T = validate_lidar_dem(dem_folder);
disp(T)
outfile = fullfile(save_folder,"LiDAR_HD_DEM_validation.csv");
writetable(T,outfile)
fprintf("Saved %s\n",outfile)

%% Save Markdown table for GitHub README

mdfile = fullfile(save_folder,"LiDAR_HD_DEM_validation.md");
fid = fopen(mdfile,"w");
fprintf(fid,...
    "| massif | DEM pixels | missing pixels | missing percentage |\n");
fprintf(fid,...
    "|---:|---:|---:|---:|\n");

for i = 1:height(T)
    fprintf(fid,...
        "| %d | %d | %d | %.3f %% |\n",...
        T.massif(i),...
        T.DEM_pixels(i),...
        T.missing_pixels(i),...
        T.missing_percentage(i));
end

fclose(fid);
fprintf("Saved %s\n",mdfile)

%% Close massif overview figure

if isvalid(OUT.fig)
    close(OUT.fig)
end

%% Alpine DEM overview

alps_folder = fullfile(dem_folder,"ALPS");
alps_dem  = fullfile(alps_folder,"DEM_ALPS.tif");
alps_mask = fullfile(alps_folder,"DEM_ALPS_mask.tif");

if isfile(alps_dem) && isfile(alps_mask)
    fprintf("\nCreating Alpine DEM overview...\n")
    plot_alps_dem(dem_folder,save_folder);
else
    fprintf("\nNo Alpine DEM found. Skipping Alpine DEM overview.\n")
end

end