function run_lidar_diagnostics(output_path,safran_shp)
%RUN_LIDAR_DIAGNOSTICS Run LiDAR HD topography quality-control workflow.
%
% DESCRIPTION
%   Generates diagnostic figures and validation tables for the LiDAR HD
%   topographic products generated by prepare_dem().
%
%   The function follows the same directory convention as prepare_dem():
%
%       CryoGridCommunity_forcing/
%       └── DEM/
%           └── LiDAR_HD_DEM_XXm/
%               ├── DEM/
%               ├── SLOPE/
%               ├── ASPECT/
%               └── ...
%
%   The workflow validates:
%       - individual SAFRAN massif DEM products
%       - merged Alpine DEM products
%       - all available Alpine topographic products
%
%
%   Alpine overview figures are automatically generated for every product
%   following the standard product structure:
%
%       PRODUCT/
%           ALPS/
%               PRODUCT_ALPS.tif
%
%   Product folders are discovered dynamically. The diagnostics workflow
%   therefore automatically supports future topographic products (e.g.
%   SLOPE, ASPECT, SVF) without requiring modifications.
%
%
% INPUTS
%
%   output_path
%       Complete LiDAR HD DEM product folder generated by prepare_dem().
%       Example:
%           CryoGridCommunity_forcing/DEM/LiDAR_HD_DEM_10m/
%
%
%   safran_shp
%       SAFRAN massif shapefile in Lambert-93 (EPSG:2154).
%
%
% OUTPUT
%
%   Creates diagnostics in:
%       LiDAR_HD_DEM_XXm/
%       └── diagnostics/
%
%   Generated files include:
%       LiDAR_HD_DEM_massifs.png
%       LiDAR_HD_<PRODUCT>_ALPS_overview.png
%       LiDAR_HD_DEM_missing_pixels.png
%       LiDAR_HD_DEM_validation.csv
%       LiDAR_HD_DEM_validation.md
%
%
% NOTES
%
%   Products are never modified.
%   Alpine product figures are generated only for products following:
%       PRODUCT/
%           ALPS/
%               PRODUCT_ALPS.tif
%
%   The workflow assumes that prepare_dem() has already generated the DEM
%   products and that all topographic products use the same Lambert-93 grid.
%
%
% SEE ALSO
%
%   prepare_dem
%   merge_massif_DEMs
%   compute_dem_derivatives
%   clip_topography_products
%   plot_alps_topography
%   validate_lidar_dem
%


%% Paths

dem_folder  = fullfile(output_path,"DEM");
save_folder = fullfile(output_path,"diagnostics");


if ~isfolder(output_path)
    error("DEM product folder not found: %s",output_path)
end

if ~isfolder(dem_folder)
    error("DEM folder not found: %s",dem_folder)
end

if ~isfolder(save_folder)
    mkdir(save_folder)
end

%% DEM overview

fprintf("\nCreating DEM overview...\n")
OUT = plot_all_lidar_massifs(dem_folder,safran_shp,save_folder);

%% Missing pixels

fprintf("\nCreating missing pixel plot...\n")
plot_lidar_missing_pixels(OUT,save_folder);

%% Validation table

fprintf("\nCreating validation table...\n")
T = validate_lidar_dem(dem_folder);
disp(T)
outfile = fullfile(save_folder,"LiDAR_HD_DEM_validation.csv");
writetable(T,outfile)
fprintf("Saved %s\n",outfile)

%% Markdown validation table

mdfile = fullfile(save_folder,"LiDAR_HD_DEM_validation.md");
fid = fopen(mdfile,"w");
fprintf(fid,...
    "| massif | DEM pixels | missing pixels | missing percentage |\n");
fprintf(fid,...
    "|---:|---:|---:|---:|\n");

for i = 1:height(T)
    fprintf(fid,...
        "| %d | %d | %d | %.3f %% |\n",...
        T.massif(i),...
        T.DEM_pixels(i),...
        T.missing_pixels(i),...
        T.missing_percentage(i));
end

fclose(fid);
fprintf("Saved %s\n",mdfile)

%% Close massif overview

if isvalid(OUT.fig)
    close(OUT.fig)
end

%% Discover Alpine topography products

fprintf("\nSearching Alpine topography products...\n")

folders = dir(output_path);
products = {};

for i = 1:numel(folders)
    if ~folders(i).isdir
        continue
    end

    name = folders(i).name;
    if startsWith(name,".")
        continue
    end

    % Check standard product structure:
    %
    % PRODUCT/
    %     ALPS/
    %         PRODUCT_ALPS.tif

    product_file = fullfile( ...
        output_path,...
        name,...
        "ALPS",...
        sprintf("%s_ALPS.tif",name));

    if isfile(product_file)
        products{end+1} = name;
    end
end

if isempty(products)
    fprintf("No Alpine topography products found.\n")
else
    fprintf("Found %d Alpine products:\n",numel(products))
    disp(products')
    for i = 1:numel(products)
        product = products{i};
        fprintf("\nCreating Alpine %s overview...\n",product)
        plot_alps_topography(output_path,product,save_folder);
    end
end

fprintf("\nLiDAR diagnostics complete.\n")

end