function run_lidar_diagnostics( ...
    output_path, ...
    safran_shp, ...
    varargin)

%RUN_LIDAR_DIAGNOSTICS
% Run LiDAR HD topography quality-control and diagnostic plots.
%
% DESCRIPTION
%   Generates diagnostic figures and validation tables for the LiDAR HD
%   topographic products generated by prepare_dem().
%
%   Standard product structure:
%
%       LiDAR_HD_DEM_XXm/
%       ├── DEM/
%       │   ├── ALPS/DEM_ALPS.tif
%       │   └── ...
%       ├── SLOPE/
%       │   ├── ALPS/SLOPE_ALPS.tif
%       │   └── ...
%       ├── ASPECT/
%       │   ├── ALPS/ASPECT_ALPS.tif
%       │   └── ...
%       ├── SVF/
%       │   └── ALPS/SVF_ALPS.tif
%       ├── SVF_naive/
%       │   └── ...
%       └── diagnostics/
%
%   Alpine products are discovered dynamically from:
%
%       PRODUCT/ALPS/PRODUCT_ALPS.tif
%
%   The diagnostic workflow is:
%
%       1. Discover Alpine products
%       2. Compute Alpine visualization bounds
%       3. Create DEM massif overview
%       4. Create missing-pixel diagnostic
%       5. Create DEM validation tables
%       6. Create Alpine overview plots
%       7. Optionally create one massif topography overview
%
%   The visualization bounds are computed once from the complete Alpine
%   products and reused by all subsequent diagnostic plots. This ensures
%   that Alpine and massif figures use exactly the same color scales.
%
% INPUTS
%
%   output_path
%       Root LiDAR HD DEM product folder.
%
%   safran_shp
%       SAFRAN massif shapefile in Lambert-93 (EPSG:2154).
%
% OPTIONAL INPUT
%
%   massif_number
%       SAFRAN massif number to additionally plot.
%
%       Example:
%
%           run_lidar_diagnostics( ...
%               output_path, ...
%               safran_shp, ...
%               1)
%
%       If omitted, no individual massif figure is generated.
%
% OUTPUT
%
%   Diagnostic figures and validation tables are written to:
%
%       output_path/diagnostics/
%
% NOTES
%
%   Products are never modified.
%
%   Visualization conventions are centralized in:
%
%       get_topography_colormap()
%
%   Visualization downsampling is centralized in:
%
%       downsample_topography()
%
%   Alpine visualization bounds are centralized for the complete
%   diagnostic run and reused by all plots.
%
%   Standard visualization conventions:
%
%       DEM        : actual Alpine range, theoretical [0 5000] fallback
%       SLOPE      : actual Alpine range, theoretical [0 90] fallback
%       ASPECT     : cyclic [0 360]
%       SVF        : actual Alpine range, theoretical [0 1] fallback
%       SVF_naive  : actual Alpine range, theoretical [0 1] fallback
%
%   NoData pixels are displayed as white.
%
% SEE ALSO
%
%   prepare_dem
%   compute_dem_derivatives
%   compute_skyview_factor_alps
%   compute_naive_svf
%   plot_all_lidar_massifs
%   plot_lidar_missing_pixels
%   plot_alps_topography
%   plot_massif_topography
%   get_alpine_topography_bounds
%   get_topography_colormap
%   downsample_topography
%   validate_lidar_dem

%% ========================================================================
% Parse optional massif number
% ========================================================================

massif_number = [];

if numel(varargin) > 1

    error( ...
        "run_lidar_diagnostics accepts at most one optional argument: " + ...
        "massif_number.")

end

if ~isempty(varargin)

    massif_number = varargin{1};

    if ~isscalar(massif_number) || ...
            ~isfinite(massif_number) || ...
            massif_number ~= round(massif_number) || ...
            massif_number < 1

        error( ...
            "massif_number must be a positive integer.")

    end

end

%% ========================================================================
% Paths
% ========================================================================

dem_folder = fullfile(output_path,"DEM");

save_folder = fullfile( ...
    output_path, ...
    "diagnostics");

if ~isfolder(output_path)

    error( ...
        "DEM product folder not found: %s", ...
        output_path)

end

if ~isfolder(dem_folder)

    error( ...
        "DEM folder not found: %s", ...
        dem_folder)

end

if ~isfolder(save_folder)

    mkdir(save_folder)

end

%% ========================================================================
% Step 1 - Discover Alpine topography products
% ========================================================================

fprintf("\n")
fprintf("============================================================\n")
fprintf(" LiDAR HD diagnostic workflow\n")
fprintf("============================================================\n")

fprintf("\nSearching Alpine topography products...\n")

folders = dir(output_path);

products = {};

for i = 1:numel(folders)

    if ~folders(i).isdir
        continue
    end

    name = folders(i).name;

    if startsWith(name,".")
        continue
    end

    % Standard Alpine product structure:
    %
    % PRODUCT/
    %     ALPS/
    %         PRODUCT_ALPS.tif

    product_file = fullfile( ...
        output_path, ...
        name, ...
        "ALPS", ...
        sprintf("%s_ALPS.tif",name));

    if isfile(product_file)

        products{end+1} = name;

    end

end

if isempty(products)

    error( ...
        "No Alpine topography products found in: %s", ...
        output_path)

end

fprintf( ...
    "Found %d Alpine products:\n", ...
    numel(products))

disp(products')

%% ========================================================================
% Step 2 - Compute Alpine visualization bounds
% ========================================================================

fprintf("\n")
fprintf("============================================================\n")
fprintf(" STEP 2 - Compute Alpine visualization bounds\n")
fprintf("============================================================\n")

bounds = get_topography_bounds( ...
    output_path, ...
    products);

fprintf("\nAlpine visualization bounds:\n")

for i = 1:numel(products)

    product = products{i};

    field = matlab.lang.makeValidName(product);

    if isfield(bounds,field)

        fprintf( ...
            "  %-12s : [%g %g]\n", ...
            product, ...
            bounds.(field)(1), ...
            bounds.(field)(2));

    end

end

%% ========================================================================
% Step 3 - DEM massif overview
% ========================================================================

fprintf("\n")
fprintf("============================================================\n")
fprintf(" STEP 3 - Create DEM massif overview\n")
fprintf("============================================================\n")

OUT = plot_all_lidar_massifs( ...
    dem_folder, ...
    safran_shp, ...
    save_folder, ...
    bounds.DEM);

%% ========================================================================
% Step 4 - Missing pixel diagnostic
% ========================================================================

fprintf("\n")
fprintf("============================================================\n")
fprintf(" STEP 4 - Create missing pixel diagnostic\n")
fprintf("============================================================\n")

plot_lidar_missing_pixels( ...
    OUT, ...
    save_folder);

%% ========================================================================
% Step 5 - DEM validation table
% ========================================================================

fprintf("\n")
fprintf("============================================================\n")
fprintf(" STEP 5 - Validate DEM products\n")
fprintf("============================================================\n")

T = validate_lidar_dem(dem_folder);

disp(T)

%% CSV

outfile = fullfile( ...
    save_folder, ...
    "LiDAR_HD_DEM_validation.csv");

writetable(T,outfile)

fprintf("Saved %s\n",outfile)

%% Markdown

mdfile = fullfile( ...
    save_folder, ...
    "LiDAR_HD_DEM_validation.md");

fid = fopen(mdfile,"w");

if fid == -1

    error( ...
        "Could not open validation markdown file for writing: %s", ...
        mdfile)

end

fprintf( ...
    fid, ...
    "| massif | DEM pixels | missing pixels | missing percentage |\n");

fprintf( ...
    fid, ...
    "|---:|---:|---:|---:|\n");

for i = 1:height(T)

    fprintf( ...
        fid, ...
        "| %d | %d | %d | %.3f %% |\n", ...
        T.massif(i), ...
        T.DEM_pixels(i), ...
        T.missing_pixels(i), ...
        T.missing_percentage(i));

end

fclose(fid);

fprintf("Saved %s\n",mdfile)

%% ========================================================================
% Close DEM overview
% ========================================================================

if isfield(OUT,"fig") && ...
        ~isempty(OUT.fig) && ...
        isvalid(OUT.fig)

    close(OUT.fig)

end

%% ========================================================================
% Step 6 - Alpine product overviews
% ========================================================================

fprintf("\n")
fprintf("============================================================\n")
fprintf(" STEP 6 - Create Alpine topography overviews\n")
fprintf("============================================================\n")

for i = 1:numel(products)

    product = products{i};

    fprintf( ...
        "\nCreating Alpine %s overview...\n", ...
        product)

    plot_alps_topography( ...
        output_path, ...
        product, ...
        save_folder, ...
        bounds);

end

%% ========================================================================
% Step 7 - Optional massif overview
% ========================================================================

if ~isempty(massif_number)

    fprintf("\n")
    fprintf("============================================================\n")
    fprintf( ...
        " STEP 7 - Create massif %02d topography overview\n", ...
        massif_number)
    fprintf("============================================================\n")

    plot_massif_topography( ...
        output_path, ...
        massif_number, ...
        bounds);

end

%% ========================================================================
% Cleanup
% ========================================================================

% Explicitly release potentially large diagnostic arrays from this
% function without modifying the user's base workspace.

clear OUT
clear bounds
clear products
clear folders
clear T

fprintf("\n")
fprintf("============================================================\n")
fprintf(" LiDAR diagnostics complete.\n")
fprintf("============================================================\n")

copyfile( ...
    fullfile(output_path,"diagnostics"), ...
    fullfile(fileparts(mfilename("fullpath")),"diagnostics"), ...
    "f");

end