function build_final_mask(geology_path,dem_path)
%BUILD_FINAL_MASK Build final CryoGrid-validity masks for SAFRAN massifs.
%
% DESCRIPTION
%   Creates a final validity mask for each SAFRAN massif by requiring that
%   every pixel contains valid:
%
%       - DEM elevation
%       - slope
%       - aspect
%       - geology
%
%   The original DEM mask defines the baseline modelling domain. A pixel
%   is considered originally valid only when:
%
%       DEM_mask == 1
%       AND
%       DEM contains a valid elevation value.
%
%   The final mask additionally requires valid slope, aspect and geology:
%
%       DEM_mask
%       AND valid DEM
%       AND valid slope
%       AND valid aspect
%       AND valid geology
%
%   The resulting mask is:
%
%       1 = valid for CryoGrid
%       0 = at least one required product is invalid
%
%   The output mask uses the exact DEM grid of each massif. No resampling
%   or interpolation is performed.
%
%
% INPUTS
%
%   dem_path
%       LiDAR_HD_DEM_XXm directory generated by prepare_dem().
%
%   geology_path
%       Root directory of the generated BRGM geology products.
%
%
% OUTPUT
%
%   masking_log.csv
%       Table containing one row per massif with:
%
%           massif_number
%           total_pixel_count
%           original_valid_pixels
%           final_valid_pixels
%           subtracted_pixels
%           subtracted_topography_pixels
%           subtracted_geology_pixels
%           subtracted_both_pixels
%           original_valid_pixels_percentage
%           final_valid_pixels_percentage
%           subtracted_pixels_percentage
%           subtracted_topography_percentage
%           subtracted_geology_percentage
%           subtracted_both_percentage
%
%   Also creates:
%
%       dem_path/
%           MASK/
%               MASK_massif_XX.tif
%               masking_log.csv
%
%
% NOTES
%
%   DEM, slope and aspect NoData values are identified using values <= -9000
%   or non-finite values.
%
%   Geology NoData is identified using values <= -9000 or non-finite values.
%
%   All products must have the same raster size and spatial extent as the
%   corresponding massif DEM.
%
%   The three loss categories are mutually exclusive:
%
%       topography only
%       geology only
%       both topography and geology
%
%   Consequently:
%
%       subtracted_pixels =
%           subtracted_topography_pixels +
%           subtracted_geology_pixels +
%           subtracted_both_pixels
%
%
% SEE ALSO
%
%   prepare_dem
%   prepare_geology
%


%% Paths

dem_folder     = fullfile(dem_path,"DEM");
slope_folder   = fullfile(dem_path,"SLOPE");
aspect_folder  = fullfile(dem_path,"ASPECT");
geology_folder = fullfile(geology_path,"processed","raster");
mask_folder    = fullfile(dem_path,"MASK");


if ~isfolder(dem_folder)
    error("DEM folder not found: %s",dem_folder)
end

if ~isfolder(slope_folder)
    error("SLOPE folder not found: %s",slope_folder)
end

if ~isfolder(aspect_folder)
    error("ASPECT folder not found: %s",aspect_folder)
end

if ~isfolder(geology_folder)
    error("Geology raster folder not found: %s",geology_folder)
end

if ~isfolder(mask_folder)
    mkdir(mask_folder)
end

%% Discover massif DEMs

dem_files = dir(fullfile(dem_folder,"DEM_massif_*.tif"));
if isempty(dem_files)
    error("No massif DEMs found in: %s",dem_folder)
end
fprintf("Found %d massif DEMs\n",numel(dem_files))

%% Preallocate summary

n = numel(dem_files);

massif_number = zeros(n,1);

total_pixel_count = zeros(n,1);

original_valid_pixels = zeros(n,1);
original_valid_pixels_percentage = zeros(n,1);

final_valid_pixels = zeros(n,1);
final_valid_pixels_percentage = zeros(n,1);

subtracted_pixels = zeros(n,1);
subtracted_pixels_percentage = zeros(n,1);

subtracted_topography_pixels = zeros(n,1);
subtracted_topography_percentage = zeros(n,1);

subtracted_geology_pixels = zeros(n,1);
subtracted_geology_percentage = zeros(n,1);

subtracted_both_pixels = zeros(n,1);
subtracted_both_percentage = zeros(n,1);


%% Massif loop

for i = 1:n
    name = dem_files(i).name;

    %% Identify massif number
    token = regexp(name,'DEM_massif_(\d+)\.tif','tokens','once');
    if isempty(token)
        error("Could not determine massif number from: %s",name)
    end

    id = token{1};
    number = str2double(id);
    massif_number(i) = number;

    %% Output mask
    output_file = fullfile(mask_folder,sprintf("MASK_massif_%s.tif",id));

    %% Read DEM
    dem_file = fullfile(dem_folder,name);
    [DEM,Rdem] = readgeoraster(dem_file);
    DEM = single(DEM);

    %% Read original DEM mask
    dem_mask_file = fullfile(dem_folder,sprintf("DEM_mask_massif_%s.tif",id));
    if ~isfile(dem_mask_file)
        error("Missing DEM mask: %s",dem_mask_file)
    end

    [DEM_MASK,Rdem_mask] = readgeoraster(dem_mask_file);
    check_grid(Rdem,Rdem_mask,"DEM_MASK",id);
    DEM_MASK = logical(DEM_MASK);

    %% Original DEM validity

    valid_DEM = DEM_MASK & isfinite(DEM) & DEM > -9000;

    %% Read slope

    slope_file = fullfile(slope_folder,sprintf("SLOPE_massif_%s.tif",id));
    if ~isfile(slope_file)
        error("Missing slope file: %s",slope_file)
    end

    [SLOPE,Rslope] = readgeoraster(slope_file);
    SLOPE = single(SLOPE);
    check_grid(Rdem,Rslope,"SLOPE",id);

    valid_SLOPE = isfinite(SLOPE) & SLOPE > -9000;

    %% Read aspect

    aspect_file = fullfile(aspect_folder,...
        sprintf("ASPECT_massif_%s.tif",id));

    if ~isfile(aspect_file)
        error("Missing aspect file: %s",aspect_file)
    end

    [ASPECT,Raspect] = readgeoraster(aspect_file);
    ASPECT = single(ASPECT);
    check_grid(Rdem,Raspect,"ASPECT",id);
    valid_ASPECT = isfinite(ASPECT) & ASPECT > -9000;

    %% Read geology

    geology_file = fullfile(geology_folder,...
        sprintf("GEOLOGY_massif_%s.tif",id));

    if ~isfile(geology_file)
        error("Missing geology file: %s",geology_file)
    end

    [GEOLOGY,Rgeology] = readgeoraster(geology_file);
    check_grid(Rdem,Rgeology,"GEOLOGY",id);
    valid_GEOLOGY = isfinite(GEOLOGY) & GEOLOGY > -9000;

    %% Basic statistics

    total_pixel_count(i) = numel(DEM);
    original_valid_pixels(i) = nnz(valid_DEM);
    original_valid_pixels_percentage(i) = ...
        100 * original_valid_pixels(i) / ...
        total_pixel_count(i);

    %% Identify mutually exclusive losses

    valid_topography = valid_SLOPE &  valid_ASPECT;
    topography_invalid = ~valid_topography;
    geology_invalid = ~valid_GEOLOGY;

    % Original-valid pixels lost only because of topography.
    topography_loss = valid_DEM & topography_invalid & ~geology_invalid;

    % Original-valid pixels lost only because of geology.
    geology_loss = valid_DEM & ~topography_invalid & geology_invalid;


    % Original-valid pixels lost because both categories are invalid.
    both_loss = valid_DEM & topography_invalid & geology_invalid;


    %% Final validity mask
    FINAL_MASK = valid_DEM & valid_topography & valid_GEOLOGY;
    FINAL_MASK = uint8(FINAL_MASK);

    %% Final statistics
    final_valid_pixels(i) = nnz(FINAL_MASK);
    final_valid_pixels_percentage(i) = ...
        100 * final_valid_pixels(i) / ...
        total_pixel_count(i);

    %% Loss statistics

    subtracted_topography_pixels(i) = nnz(topography_loss);
    subtracted_topography_percentage(i) = ...
        100 * subtracted_topography_pixels(i) / ...
        original_valid_pixels(i);

    subtracted_geology_pixels(i) = nnz(geology_loss);
    subtracted_geology_percentage(i) = ...
        100 * subtracted_geology_pixels(i) / ...
        original_valid_pixels(i);

    subtracted_both_pixels(i) = nnz(both_loss);
    subtracted_both_percentage(i) = ...
        100 * subtracted_both_pixels(i) / ...
        original_valid_pixels(i);

    %% Total subtraction
    subtracted_pixels(i) = ...
        subtracted_topography_pixels(i) + ...
        subtracted_geology_pixels(i) + ...
        subtracted_both_pixels(i);

    subtracted_pixels_percentage(i) = ...
        100 * subtracted_pixels(i) / ...
        original_valid_pixels(i);

    %% Consistency check

    if subtracted_pixels(i) ~= ...
            original_valid_pixels(i) - ...
            final_valid_pixels(i)
        error("Internal mask accounting error for massif %s",id)
    end

    %% Report

    fprintf( ...
        "Total pixels:          %d\n",...
        total_pixel_count(i))

    fprintf( ...
        "Original valid:        %d (%.3f %%)\n",...
        original_valid_pixels(i),...
        original_valid_pixels_percentage(i))

    fprintf( ...
        "Final valid:           %d (%.3f %%)\n",...
        final_valid_pixels(i),...
        final_valid_pixels_percentage(i))

    fprintf( ...
        "Subtracted total:      %d (%.3f %%)\n",...
        subtracted_pixels(i), ...
        subtracted_pixels_percentage(i))

    fprintf( ...
        "Topography only:       %d (%.3f %%)\n",...
        subtracted_topography_pixels(i),...
        subtracted_topography_percentage(i))

    fprintf( ...
        "Geology only:          %d (%.3f %%)\n",...
        subtracted_geology_pixels(i),...
        subtracted_geology_percentage(i))

    fprintf( ...
        "Both:                  %d (%.3f %%)\n",...
        subtracted_both_pixels(i),...
        subtracted_both_percentage(i))


    %% Save final mask

    geotiffwrite(output_file,FINAL_MASK,Rdem,"CoordRefSysCode",2154);
    fprintf("Saved %s\n",output_file)

end


%% Summary table

T = table( ...
    massif_number,...
    total_pixel_count,...
    original_valid_pixels,...
    final_valid_pixels,...
    subtracted_pixels,...
    subtracted_topography_pixels,...
    subtracted_geology_pixels,...
    subtracted_both_pixels,...
    original_valid_pixels_percentage,...
    final_valid_pixels_percentage, ...
    subtracted_pixels_percentage,...
    subtracted_topography_percentage,...
    subtracted_geology_percentage,...
    subtracted_both_percentage);

%% Save masking log
writetable(T,fullfile(mask_folder,"masking_log.csv"));
fprintf("Saved masking log: %s\n",fullfile(mask_folder,"masking_log.csv"));

%% Summary

fprintf("\n============================================\n")
fprintf("Final mask generation complete\n")
fprintf("============================================\n")

fprintf( ...
    "Total original valid pixels: %d\n",...
    sum(original_valid_pixels))

fprintf( ...
    "Total final valid pixels:    %d\n",...
    sum(final_valid_pixels))

fprintf( ...
    "Total subtracted pixels:     %d\n",...
    sum(subtracted_pixels))

fprintf( ...
    "Topography only:             %d\n",...
    sum(subtracted_topography_pixels))

fprintf( ...
    "Geology only:                %d\n",...
    sum(subtracted_geology_pixels))

fprintf( ...
    "Both:                        %d\n",...
    sum(subtracted_both_pixels))

fprintf( ...
    "Overall final validity:      %.3f %%\n",...
    100 * sum(final_valid_pixels) / ...
    sum(total_pixel_count))

end


%% Local function
function check_grid(Rref,Rtest,product,id)

if ~isequal( ...
        Rref.RasterSize,...
        Rtest.RasterSize) || ...
   any(Rref.XWorldLimits ~= Rtest.XWorldLimits) || ...
   any(Rref.YWorldLimits ~= Rtest.YWorldLimits)
    error("Grid mismatch between DEM and %s for massif %s",product,id)
end

end