function clip_topography_products(dem_folder,varargin)
%CLIP_TOPOGRAPHY_PRODUCTS Clip Alpine terrain products to SAFRAN massifs.
%
% DESCRIPTION
%   Extracts massif-scale topographic products from continuous Alpine
%   products generated by compute_dem_derivatives().
%
%   Available products are detected automatically. Any folder inside
%   dem_folder containing an ALPS subfolder with a matching Alpine GeoTIFF:
%
%       PRODUCT/
%           ALPS/
%               PRODUCT_ALPS.tif
%
%   is considered a valid topographic product and is clipped.
%
%   Examples:
%
%       SLOPE/
%           ALPS/
%               SLOPE_ALPS.tif
%
%       ASPECT/
%           ALPS/
%               ASPECT_ALPS.tif
%
%   The clipping is performed by matching the exact massif DEM grid inside
%   the larger Alpine product grid. No resampling or interpolation is
%   performed.
%
%   The DEM grid defines:
%
%       - spatial extent
%       - resolution
%       - pixel alignment
%
%   The corresponding DEM mask is applied:
%
%       1 = keep value
%       0 = set to NoData (-9999)
%
%
% INPUT
%
%   dem_folder
%       Root LiDAR_HD_DEM_xx folder containing DEM and topographic
%       product folders.
%
%
% OPTIONS
%
%   "Overwrite"
%       Recompute existing massif products.
%       Default = false
%
%
% OUTPUT
%
%   Creates one massif GeoTIFF per detected product:
%       PRODUCT/
%           PRODUCT_massif_XX.tif
%
%
% SEE ALSO
%
%   compute_dem_derivatives
%   merge_massif_DEMs


%% Options

p = inputParser;
addParameter(p,"Overwrite",false)
parse(p,varargin{:})
overwrite = p.Results.Overwrite;

%% Discover available topography products

folders = dir(dem_folder);
products = {};

for i = 1:numel(folders)
    name = folders(i).name;

    % Ignore files and hidden folders
    if ~folders(i).isdir || startsWith(name,".")
        continue
    end

    % DEM contains the reference elevation data, not a derivative
    if strcmpi(name,"DEM")
        continue
    end

    % Check for matching Alpine product
    alpine_file = fullfile( ...
        dem_folder,...
        name,...
        "ALPS",...
        sprintf("%s_ALPS.tif",name));

    if isfile(alpine_file)
        products{end+1} = name;
    end
end

if isempty(products)
    error("No Alpine topography products found in %s",dem_folder)
end

% Ensure reproducible processing order
products = sort(products);

fprintf("Found %d topography products:\n",numel(products))

for i = 1:numel(products)
    fprintf("  %s\n",products{i})
end

%% Find massif DEMs

dem_product_folder = fullfile(dem_folder,"DEM");
dem_files = dir(fullfile(dem_product_folder,"DEM_massif_*.tif"));

if isempty(dem_files)
    error("No massif DEM files found")
end

fprintf("Found %d massif DEMs\n",numel(dem_files))

%% Determine remaining work before loading Alpine products

process = false(numel(dem_files),1);

for k = 1:numel(dem_files)
    token = regexp(dem_files(k).name,'DEM_massif_(\d+)','tokens');
    massif = token{1}{1};
    for i = 1:numel(products)
        output_file = fullfile( ...
            dem_folder,...
            products{i},...
            sprintf("%s_massif_%s.tif",products{i},massif));
        if overwrite || ~isfile(output_file)
            process(k) = true;
            break
        end
    end
end

if ~any(process)
    fprintf("All topography products already exist. Nothing to do.\n")
    return
end

dem_files = dem_files(process);

%% Check Alpine products

for i = 1:numel(products)
    alpine_file = fullfile( ...
        dem_folder,...
        products{i},...
        "ALPS",...
        sprintf("%s_ALPS.tif",products{i}));
    if ~isfile(alpine_file)
        error("Missing Alpine product: %s",alpine_file)
    end
end


%% Load Alpine products once

fprintf("Loading Alpine topography products\n")
TOPO = struct();

for i = 1:numel(products)
    product = products{i};

    alpine_file = fullfile( ...
        dem_folder,...
        product,...
        "ALPS",...
        sprintf("%s_ALPS.tif",product));

    [Z,R] = readgeoraster(alpine_file);

    TOPO.(product).data = single(Z);
    TOPO.(product).R = R;
end

%% Check common Alpine grid

Rtopo = TOPO.(products{1}).R;

for i = 2:numel(products)
    R = TOPO.(products{i}).R;
    if ~isequal(R.RasterSize,Rtopo.RasterSize) || ...
       any(R.XWorldLimits ~= Rtopo.XWorldLimits) || ...
       any(R.YWorldLimits ~= Rtopo.YWorldLimits)
        error("Alpine products do not share the same grid")
    end
end

dx = Rtopo.CellExtentInWorldX;
dy = Rtopo.CellExtentInWorldY;

%% Process massifs

for k = 1:numel(dem_files)
    dem_name = dem_files(k).name;
    token = regexp(dem_name,'DEM_massif_(\d+)','tokens');
    massif = token{1}{1};
    fprintf("\nProcessing massif %s\n",massif)

    %% Read massif grid

    dem_file = fullfile(dem_product_folder,dem_name);
    [~,Rdem] = readgeoraster(dem_file);

    %% Read massif mask

    mask_file = fullfile( ...
        dem_product_folder,...
        sprintf("DEM_mask_massif_%s.tif",massif));

    if ~isfile(mask_file)
        error("Missing mask: %s",mask_file)
    end

    M = readgeoraster(mask_file);
    M = logical(M);

    %% Locate massif inside Alpine grid

    col0 = round((Rdem.XWorldLimits(1)-Rtopo.XWorldLimits(1))/dx ) + 1;
    row0 = round((Rtopo.YWorldLimits(2)-Rdem.YWorldLimits(2))/dy ) + 1;

    rows = row0:(row0 + Rdem.RasterSize(1)-1);
    cols = col0:(col0 + Rdem.RasterSize(2)-1);

    if min(rows)<1 || max(rows)>Rtopo.RasterSize(1) || ...
       min(cols)<1 || max(cols)>Rtopo.RasterSize(2)
        error("Massif %s outside Alpine product grid",massif)
    end

    %% Extract and save products

    for i = 1:numel(products)
        product = products{i};
        fprintf("  Writing %s\n",product)
        Z = TOPO.(product).data(rows,cols);

        %% Apply massif mask

        Z(~M) = -9999;
        Z = single(Z);

        %% Verify output size

        if ~isequal(size(Z),Rdem.RasterSize)
            error("Raster size mismatch for massif %s",massif)
        end

        %% Output

        output_file = fullfile( ...
            dem_folder,...
            product,...
            sprintf("%s_massif_%s.tif",product,massif));

        if ~isfolder(fileparts(output_file))
            mkdir(fileparts(output_file))
        end

        geotiffwrite(output_file,Z,Rdem,"CoordRefSysCode",2154);

    end
end

fprintf("\nTopography clipping complete\n")

end