function compute_skyview_factor(dem_folder,varargin)
%COMPUTE_SKYVIEW_FACTOR Compute slope-based sky-view factor products.
%
% DESCRIPTION
%   Computes a sky-view factor (SVF) from the standard GIS slope products
%   generated by compute_dem_derivatives().
%
%   The SVF is calculated using the slope-only approximation:
%
%       SVF = cos²(slope / 2)
%
%   where slope is expressed in degrees.
%
%   This approximation gives:
%
%       slope = 0°   -> SVF = 1
%       slope = 90°  -> SVF = 0.5
%       slope = 180° -> SVF = 0
%
%   The resulting SVF therefore represents a local slope-based estimate
%   of sky visibility. It does NOT account for surrounding terrain
%   horizons or topographic obstruction.
%
%   Standard SLOPE products are preserved unchanged.
%   SVF products are generated as a separate product folder.
%
%
% INPUT
%
%   dem_folder
%       Root LiDAR_HD_DEM_XXm product folder.
%
%       Expected structure:
%
%           dem_folder/
%               SLOPE/
%                   SLOPE_massif_XX.tif
%
%
% OPTIONS
%
%   "Overwrite"
%       Recompute existing SVF products.
%
%       Default = false
%
%
% OUTPUT
%
%   Creates:
%
%       dem_folder/
%           SVF/
%               SVF_massif_XX.tif
%
%
%   SVF values are dimensionless and theoretically range from 0 to 1.
%
%   NoData pixels are stored as -9999.
%
%
% NOTES
%
%   Only SLOPE GeoTIFF files directly contained in SLOPE/ are processed.
%   The Alpine product in SLOPE/ALPS/ is intentionally not processed.
%
%   This function uses only the local slope and therefore does not
%   calculate a horizon-based sky-view factor from surrounding terrain.
%
%
% SEE ALSO
%
%   compute_dem_derivatives
%   prepare_dem
%

%% Options

p = inputParser;
addParameter(p,"Overwrite",false)
parse(p,varargin{:})
overwrite = p.Results.Overwrite;

%% Locate source SLOPE products

slope_folder = fullfile(dem_folder,"SLOPE");
if ~isfolder(slope_folder)
    fprintf("No SLOPE folder found. Skipping SVF computation.\n")
    return
end

input_files = dir(fullfile(slope_folder,"SLOPE_*.tif"));
if isempty(input_files)
    fprintf("No SLOPE files found. Skipping SVF computation.\n")
    return
end

%% Output folder

output_folder = fullfile(dem_folder,"SVF");
if ~isfolder(output_folder)
    mkdir(output_folder)
end

%% Compute SVF

fprintf("\nComputing sky-view factor from slope...\n")
for i = 1:numel(input_files)
    input_file = fullfile(input_files(i).folder,input_files(i).name);
    output_name = strrep(input_files(i).name,"SLOPE_","SVF_");
    output_file = fullfile(output_folder,output_name);
    if isfile(output_file) && ~overwrite
        continue
    end
    fprintf("  %s\n",output_name)

    %% Read slope
    [slope,R] = readgeoraster(input_file);
    slope = single(slope);

    %% Identify NoData
    nodata = slope <= -9000;
    slope(nodata) = NaN;

    %% Compute slope-based SVF
    svf = single(cosd(slope/2).^2);

    %% Restore NoData
    svf(nodata) = -9999;

    %% Write GeoTIFF

    geotiffwrite(output_file,svf,R,"CoordRefSysCode",2154)

end

fprintf("Sky-view factor (SVF) computation complete.\n")

end