function compute_dem_derivatives(dem_folder,varargin)
%COMPUTE_DEM_DERIVATIVES Compute Alpine DEM terrain derivatives.
%
% DESCRIPTION
%   Computes slope and aspect from the continuous Alpine DEM generated by
%   merge_massif_DEMs().
%
%   Derivatives are computed on the full Alpine DEM before massif clipping
%   to avoid artificial discontinuities at SAFRAN massif boundaries.
%
%   Outputs are stored separately from the elevation data:
%
%       SLOPE/
%           ALPS/
%               SLOPE_ALPS.tif
%
%       ASPECT/
%           ALPS/
%               ASPECT_ALPS.tif
%
%   Slope:
%       degrees from horizontal
%
%   Aspect:
%       0   = North
%       90  = East
%       180 = South
%       270 = West
%
% INPUT
%   dem_folder
%       Root DEM product folder:
%           LiDAR_HD_DEM_xx/
%
% OPTIONS
%
%   "Overwrite"
%       Recompute existing derivatives.
%       Default = false
%
% NOTES
%
%   - No resampling is performed.
%   - Output grids are identical to DEM_ALPS.tif.
%   - NoData values (-9999) are preserved.
%
% SEE ALSO
%
%   merge_massif_DEMs
%   clip_dem_derivatives


%% Options

p = inputParser;
addParameter(p,"Overwrite",false)
parse(p,varargin{:})
overwrite = p.Results.Overwrite;

%% Paths

dem_file = fullfile(dem_folder,"DEM","ALPS","DEM_ALPS.tif");
slope_folder  = fullfile(dem_folder,"SLOPE","ALPS");
aspect_folder = fullfile(dem_folder,"ASPECT","ALPS");

if ~isfolder(slope_folder)
    mkdir(slope_folder)
end

if ~isfolder(aspect_folder)
    mkdir(aspect_folder)
end

slope_file  = fullfile(slope_folder,"SLOPE_ALPS.tif");
aspect_file = fullfile(aspect_folder,"ASPECT_ALPS.tif");

%% Restart logic

if isfile(slope_file) && isfile(aspect_file) && ~overwrite
    fprintf("DEM derivatives already exist. Skipping.\n")
    return
end

%% Read DEM

fprintf("Reading Alpine DEM\n")
[Z,R] = readgeoraster(dem_file);
Z = single(Z);
Z(Z<=-9000)=NaN;

%% Compute gradients

fprintf("Computing gradients\n")
dx = R.CellExtentInWorldX;
dy = R.CellExtentInWorldY;
[dzdy,dzdx] = gradient(Z,dy,dx);

%% Slope

fprintf("Computing slope\n")
SLOPE = atan(sqrt(dzdx.^2 + dzdy.^2)) * 180/pi;

%% Aspect

fprintf("Computing aspect\n")
ASPECT = atan2(dzdx,-dzdy) * 180/pi;
ASPECT(ASPECT<0) = ASPECT(ASPECT<0)+360;

%% Restore NoData

SLOPE(isnan(Z)) = -9999;
ASPECT(isnan(Z)) = -9999;

SLOPE = single(SLOPE);
ASPECT = single(ASPECT);

%% Write

fprintf("Writing slope\n")
geotiffwrite(slope_file,SLOPE,R,"CoordRefSysCode",2154);

fprintf("Writing aspect\n")
geotiffwrite(aspect_file,ASPECT,R,"CoordRefSysCode",2154);

fprintf("\nSaved:\n")
fprintf("%s\n",slope_file)
fprintf("%s\n",aspect_file)

end