function convert_aspect_to_cryogrid(dem_folder,varargin)
%CONVERT_ASPECT_TO_CRYOGRID Convert GIS aspect products to CryoGrid convention.
%
% DESCRIPTION
%   Converts standard GIS aspect products generated by
%   compute_dem_derivatives() into the aspect convention expected by
%   CryoGrid.
%
%   Input convention:
%
%       0°   = North
%       90°  = East
%       180° = South
%       270° = West
%
%   Output convention:
%
%       0°   = South
%       90°  = East
%       180° = North
%       270° = West
%
%   Conversion:
%       ASPECT_CryoGrid = mod(180 - ASPECT,360)
%
%
% INPUT
%
%   dem_folder
%       Root LiDAR_HD_DEM_xx folder.
%
%
% OUTPUT
%
%   Creates:
%       ASPECT_CryoGrid/
%           ASPECT_ALPS.tif
%           ASPECT_massif_XX.tif
%
% NOTES
%
%   The standard GIS aspect products are preserved unchanged.
%   The CryoGrid products are generated as a separate export.
%


%% Options

p = inputParser;
addParameter(p,"Overwrite",false)
parse(p,varargin{:})
overwrite = p.Results.Overwrite;

%% Locate source ASPECT products

aspect_folder = fullfile(dem_folder,"ASPECT");
if ~isfolder(aspect_folder)
    fprintf("No ASPECT folder found. Skipping CryoGrid conversion.\n")
    return
end

input_files = dir(fullfile(aspect_folder,"ASPECT*.tif"));
if isempty(input_files)
    fprintf("No ASPECT files found. Skipping CryoGrid conversion.\n")
    return
end

%% Output

output_folder = fullfile(dem_folder,"ASPECT_CryoGrid");
if ~isfolder(output_folder)
    mkdir(output_folder)
end

%% Convert

for i = 1:numel(input_files)
    input_file = fullfile(input_files(i).folder,input_files(i).name);
    output_file = fullfile(output_folder,input_files(i).name);
    if isfile(output_file) && ~overwrite
        continue
    end

    [A,R] = readgeoraster(input_file);
    A = single(A);

    nodata = A <= -9000;
    A(nodata) = NaN;

    % GIS -> CryoGrid convention
    A = mod(180-A,360);
    A(nodata) = -9999;

    geotiffwrite(output_file,A,R,"CoordRefSysCode",2154)

end

fprintf("CryoGrid aspect conversion complete\n")

end