function merge_massif_DEMs(dem_folder,varargin)
%MERGE_MASSIF_DEMS Merge SAFRAN massif DEMs into one Alpine DEM.
%
% DESCRIPTION
%   Creates a continuous Alpine DEM from individual SAFRAN massif DEM
%   products generated by prepare_dem().
%
%   The merging is performed without resampling. All massif DEMs are
%   expected to have identical:
%
%       - projection (Lambert-93 / EPSG:2154)
%       - resolution
%       - grid alignment
%       - NoData convention
%
%   When overlapping pixels occur:
%
%       1. Valid elevation data overwrite NoData values
%       2. Existing valid values are preserved
%       3. NoData remains NoData if no valid data exist
%
%   A total Alpine mask is generated as the union of all massif masks.
%
%
% INPUT
%
%   dem_folder
%       Folder containing massif DEM and mask GeoTIFF files:
%
%           DEM_massif_XX.tif
%           DEM_mask_massif_XX.tif
%
%
% OPTIONS
%
%   'Overwrite'
%       Recompute existing Alpine products.
%
%       default = false
%
%
% OUTPUT
%
%   Creates:
%
%       DEM_ALPS.tif
%           Continuous Alpine DEM mosaic.
%
%       DEM_ALPS_mask.tif
%           Binary mask representing the union of all SAFRAN massifs.
%
%           1 = inside at least one massif
%           0 = outside modelling domain
%
%
% NOTE
%
%   No interpolation is performed during merging.
%   The output grid is inherited from the first massif DEM.


%% Options

p = inputParser;
addParameter(p,"Overwrite",false)
parse(p,varargin{:})
overwrite = p.Results.Overwrite;


%% Output files

output_folder = fullfile(dem_folder,"ALPS");

if ~isfolder(output_folder)
    mkdir(output_folder)
end

dem_output  = fullfile(output_folder,"DEM_ALPS.tif");
mask_output = fullfile(output_folder,"DEM_ALPS_mask.tif");


if exist(dem_output,"file") && exist(mask_output,"file") && ~overwrite
    fprintf("ALPS DEM already exists. Skipping.\n")
    return
end


%% Find massif DEMs

files = dir(fullfile(dem_folder,"DEM_massif_*.tif"));

if isempty(files)
    error("No massif DEM files found in %s",dem_folder)
end

fprintf("Found %d massif DEMs\n",numel(files))


%% Determine global extent

[~,R0] = readgeoraster(fullfile(files(1).folder,files(1).name));


% World limits

xlim = R0.XWorldLimits;
ylim = R0.YWorldLimits;

for i = 2:numel(files)
    [~,R] = readgeoraster(fullfile(files(i).folder,files(i).name));

    if abs(R.CellExtentInWorldX - R0.CellExtentInWorldX) > 1e-6 || ...
       abs(R.CellExtentInWorldY - R0.CellExtentInWorldY) > 1e-6
        error("DEM resolutions are inconsistent")
    end

    xlim = [min(xlim(1),R.XWorldLimits(1)), ...
            max(xlim(2),R.XWorldLimits(2))];

    ylim = [min(ylim(1),R.YWorldLimits(1)), ...
            max(ylim(2),R.YWorldLimits(2))];
end


%% Create output grid

dx = R0.CellExtentInWorldX;
dy = R0.CellExtentInWorldY;

nx = round(diff(xlim)/dx);
ny = round(diff(ylim)/dy);

DEM = single(-9999);
DEM = repmat(DEM,ny,nx);

MASK = false(ny,nx);


%% Create spatial reference

Rout = maprefcells(xlim,ylim,[ny nx],"ColumnsStartFrom","north");

%% Merge DEMs

for i = 1:numel(files)
    filename = fullfile(files(i).folder,files(i).name);
    fprintf("Adding %s\n",files(i).name)
    [Z,R] = readgeoraster(filename);
    Z = single(Z);

    % Pixel indices in output grid

    col = round((R.XWorldLimits(1)-Rout.XWorldLimits(1))/dx)+1;
    row = round((Rout.YWorldLimits(2)-R.YWorldLimits(2))/dy)+1;

    rows = row:(row+size(Z,1)-1);
    cols = col:(col+size(Z,2)-1);

    current = DEM(rows,cols);

    valid_new = Z ~= -9999;
    valid_old = current ~= -9999;

    % Replace only missing values

    replace = valid_new & ~valid_old;
    current(replace) = Z(replace);
    DEM(rows,cols) = current;

    %% Merge masks

    maskfile = fullfile( ...
        files(i).folder, ...
        strrep(files(i).name,"DEM_","DEM_mask_"));

    if exist(maskfile,"file")
        M = readgeoraster(maskfile);
        MASK(rows,cols) = MASK(rows,cols) | logical(M);
    end
end

%% Save

DEM = single(DEM);
DEM(DEM == -9999) = -9999;

geotiffwrite(dem_output,DEM,Rout,"CoordRefSysCode",2154);
geotiffwrite(mask_output,uint8(MASK),Rout,"CoordRefSysCode",2154);

fprintf("\nSaved:\n%s\n%s\n",dem_output,mask_output)

end