function fig = plot_alps_dem(dem_folder,save_folder)
%PLOT_ALPS_DEM Plot merged Alpine LiDAR HD DEM.
%
% DESCRIPTION
%   Creates an overview figure of the merged Alpine DEM generated by
%   merge_massif_DEMs().
%
%   The plot displays:
%
%       - Alpine DEM elevation
%       - DEM NoData areas
%       - Alpine modelling boundary from the union massif mask
%
%   The DEM is optionally downsampled for visualization only.
%   The original GeoTIFF resolution is preserved.
%
%
% INPUTS
%
%   dem_folder
%       Folder containing the Alpine DEM products:
%
%           ALPS/
%               DEM_ALPS.tif
%               DEM_ALPS_mask.tif
%
%   save_folder
%       Output folder where the diagnostic PNG figure is saved.
%
%
% OUTPUT
%
%   fig
%       MATLAB figure handle.
%
%   Creates:
%
%       LiDAR_HD_DEM_ALPS_overview.png
%
%
% SEE ALSO
%
%   merge_massif_DEMs
%   run_lidar_diagnostics
%


%% Paths

alps_folder = fullfile(dem_folder,"ALPS");

dem_file  = fullfile(alps_folder,"DEM_ALPS.tif");
mask_file = fullfile(alps_folder,"DEM_ALPS_mask.tif");

if ~isfile(dem_file)
    error("Alpine DEM not found: %s",dem_file)
end

if ~isfile(mask_file)
    error("Alpine DEM mask not found: %s",mask_file)
end


%% Read DEM

fprintf("Reading Alpine DEM\n")

[Z,R] = readgeoraster(dem_file);
Z = single(Z);

% GeoTIFF NoData convention
Z(Z<=-9000)=NaN;


%% Downsample for plotting

plot_factor = 5;

Zplot = Z(1:plot_factor:end,1:plot_factor:end);

Rplot = maprefcells( ...
    R.XWorldLimits,...
    R.YWorldLimits,...
    size(Zplot),...
    "ColumnsStartFrom","north");

[x,y] = worldGrid(Rplot);


%% Figure

fig = figure("Visible","on","WindowState","minimized");

hold on
box on
axis equal tight

surface(x,y,Zplot,"EdgeColor","none")
colormap turbo

cb = colorbar;
cb.Label.String = "Elevation (m)";

xlabel("Lambert-93 Easting (m)")
ylabel("Lambert-93 Northing (m)")

title("IGN LiDAR HD Alpine DEM")


%% Mask boundary

fprintf("Reading Alpine mask\n")

M = readgeoraster(mask_file);
Mplot = M(1:plot_factor:end,1:plot_factor:end);

contour(x,y,Mplot,[1 1],"k","LineWidth",1);

%% Save

outfile = fullfile( ...
    save_folder,...
    "LiDAR_HD_DEM_ALPS_overview.png");

fig.Visible = "off";

exportgraphics(fig,outfile,"Resolution",300);

fprintf("Saved %s\n",outfile)

end