function OUT = plot_all_lidar_massifs( ...
    dem_folder,...
    safran_shp,...
    save_folder,...
    dem_bounds)
%PLOT_ALL_LIDAR_MASSIFS Save LiDAR DEM overview.


OUT = plot_lidar_dem_base( ...
    dem_folder,...
    safran_shp,...
    dem_bounds);


outfile = fullfile( ...
    save_folder,...
    "LiDAR_HD_DEM_massifs.png");

exportgraphics( ...
    OUT.fig,...
    outfile,...
    "Resolution",300);


fprintf("Saved %s\n",outfile)


end