function T = validate_topography_derivatives(output_path)
%VALIDATE_TOPOGRAPHY_DERIVATIVES Check derivative NoData against valid DEM.
%
% DESCRIPTION
%   Compares massif DEMs with their corresponding slope and aspect
%   products and identifies pixels where a valid DEM elevation exists but
%   the terrain derivative is missing.
%
%   This detects derivative edge effects or other invalid derivative
%   pixels that are not caused simply by the SAFRAN massif mask.
%
% INPUT
%
%   output_path
%       LiDAR_HD_DEM_XXm output directory generated by prepare_dem().
%
%       Expected structure:
%
%           output_path/
%               DEM/
%                   DEM_massif_XX.tif
%               SLOPE/
%                   SLOPE_massif_XX.tif
%               ASPECT/
%                   ASPECT_massif_XX.tif
%
%
% OUTPUT
%
%   T
%       Table containing one row per massif with:
%
%           massif
%           DEM_valid_pixels
%           slope_missing_pixels
%           slope_missing_percentage
%           aspect_missing_pixels
%           aspect_missing_percentage
%
%
% NOTES
%
%   Pixels outside the SAFRAN massif are excluded because the DEM itself
%   is invalid there.
%
%   A pixel is considered derivative-missing when:
%
%       DEM is valid
%       AND
%       derivative is NoData or NaN
%
%   The function therefore specifically measures derivative loss within
%   areas where valid elevation data exists.
%
% SEE ALSO
%
%   compute_dem_derivatives
%   clip_topography_products
%   run_lidar_diagnostics
%


%% Paths

dem_folder    = fullfile(output_path,"DEM");
slope_folder  = fullfile(output_path,"SLOPE");
aspect_folder = fullfile(output_path,"ASPECT");


if ~isfolder(dem_folder)
    error("DEM folder not found: %s",dem_folder)
end

if ~isfolder(slope_folder)
    error("SLOPE folder not found: %s",slope_folder)
end

if ~isfolder(aspect_folder)
    error("ASPECT folder not found: %s",aspect_folder)
end


%% Discover massif DEMs

dem_files = dir(fullfile(dem_folder,"DEM_massif_*.tif"));

if isempty(dem_files)
    error("No massif DEMs found in: %s",dem_folder)
end

fprintf("Found %d massif DEMs\n",numel(dem_files))


%% Preallocate

n = numel(dem_files);

massif = zeros(n,1);
DEM_valid_pixels = zeros(n,1);
slope_missing_pixels = zeros(n,1);
aspect_missing_pixels = zeros(n,1);

slope_missing_percentage = zeros(n,1);
aspect_missing_percentage = zeros(n,1);


%% Loop over massifs

for i = 1:n

    name = dem_files(i).name;

    token = regexp( ...
        name,...
        'DEM_massif_(\d+)\.tif',...
        'tokens',...
        'once');

    if isempty(token)
        error("Could not determine massif number from: %s",name)
    end

    id = token{1};
    massif(i) = str2double(id);

    fprintf("\nChecking massif %s\n",id)


    %% Read DEM

    dem_file = fullfile(dem_folder,name);

    [DEM,Rdem] = readgeoraster(dem_file);

    DEM = single(DEM);

    valid_DEM = isfinite(DEM) & DEM > -9000;

    n_valid = nnz(valid_DEM);

    DEM_valid_pixels(i) = n_valid;


    %% Slope

    slope_file = fullfile( ...
        slope_folder,...
        sprintf("SLOPE_massif_%s.tif",id));

    if ~isfile(slope_file)
        error("Missing slope file: %s",slope_file)
    end

    [SLOPE,Rslope] = readgeoraster(slope_file);

    SLOPE = single(SLOPE);

    if ~isequal(Rdem.RasterSize,Rslope.RasterSize) || ...
       any(Rdem.XWorldLimits ~= Rslope.XWorldLimits) || ...
       any(Rdem.YWorldLimits ~= Rslope.YWorldLimits)

        error("Grid mismatch between DEM and slope for massif %s",id)
    end

    valid_SLOPE = isfinite(SLOPE) & SLOPE > -9000;

    missing_slope = valid_DEM & ~valid_SLOPE;

    slope_missing_pixels(i) = nnz(missing_slope);

    if n_valid > 0
        slope_missing_percentage(i) = ...
            100 * slope_missing_pixels(i) / n_valid;
    end


    %% Aspect

    aspect_file = fullfile( ...
        aspect_folder,...
        sprintf("ASPECT_massif_%s.tif",id));

    if ~isfile(aspect_file)
        error("Missing aspect file: %s",aspect_file)
    end

    [ASPECT,Raspect] = readgeoraster(aspect_file);

    ASPECT = single(ASPECT);

    if ~isequal(Rdem.RasterSize,Raspect.RasterSize) || ...
       any(Rdem.XWorldLimits ~= Raspect.XWorldLimits) || ...
       any(Rdem.YWorldLimits ~= Raspect.YWorldLimits)

        error("Grid mismatch between DEM and aspect for massif %s",id)
    end

    valid_ASPECT = isfinite(ASPECT) & ASPECT > -9000;

    missing_aspect = valid_DEM & ~valid_ASPECT;

    aspect_missing_pixels(i) = nnz(missing_aspect);

    if n_valid > 0
        aspect_missing_percentage(i) = ...
            100 * aspect_missing_pixels(i) / n_valid;
    end


    %% Report

    fprintf( ...
        "  Valid DEM pixels: %d\n",...
        n_valid)

    fprintf( ...
        "  Missing slope:    %d (%.3f %%)\n",...
        slope_missing_pixels(i),...
        slope_missing_percentage(i))

    fprintf( ...
        "  Missing aspect:   %d (%.3f %%)\n",...
        aspect_missing_pixels(i),...
        aspect_missing_percentage(i))

end


%% Table

T = table( ...
    massif,...
    DEM_valid_pixels,...
    slope_missing_pixels,...
    slope_missing_percentage,...
    aspect_missing_pixels,...
    aspect_missing_percentage);


%% Summary

fprintf("\n============================================\n")
fprintf("Derivative validation complete\n")
fprintf("============================================\n")

fprintf( ...
    "Total valid DEM pixels: %d\n",...
    sum(DEM_valid_pixels))

fprintf( ...
    "Total missing slope pixels: %d (%.3f %%)\n",...
    sum(slope_missing_pixels),...
    100 * sum(slope_missing_pixels) / sum(DEM_valid_pixels))

fprintf( ...
    "Total missing aspect pixels: %d (%.3f %%)\n",...
    sum(aspect_missing_pixels),...
    100 * sum(aspect_missing_pixels) / sum(DEM_valid_pixels))

end